### ISSUE TITLE
Enable user to delete requests

### ISSUE THREAD

**Issue by duckduckcodes** [duckduckcodes/devsensei#11]
We need to implement a way for the user to delete existing requests from the UI, such as a button or context menu. Make sure to properly update the state to remove the deleted request.

**Comment by aao056** [comment]
Hi there.

Do you mean the enabling users to delete the requests from the main screen (get one users and get all users)? 

I see there is already a delete button there, the state just need to be updated when the button is clicked.

**Comment by duckduckcodes** [comment]
yeah exactly, i just finished working on this, so i'll close the issue, but feel free to explore other issues if you want
